name: Release qiniu-doc-checker

on:
  push:
    tags:
      - v*

permissions: write-all

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
          body: |
            Release Notes

  build_and_upload:
    name: Build and Upload
    needs: create_release
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ macos, windows, ubuntu ]

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1

      - name: Set version by tag
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      # 查看Dart版本
      - name: Report version
        run: dart --version

      # 导入依赖
      - name: Install dependencies
        run: dart pub get

      - name: Compile
        if: matrix.os == 'windows'
        run: |
          dart compile exe bin/qiniu_doc_checker.dart -o qiniu_doc_checker.exe

      - uses: vimtor/action-zip@v1
        if: matrix.os == 'windows'
        with:
          files: qiniu_doc_checker.exe config.yaml
          dest: qiniu_doc_checker.zip

      - name: Compile
        if: matrix.os != 'windows'
        run: |
          dart compile exe bin/qiniu_doc_checker.dart -o qiniu_doc_checker

      - name: Compress binary file
        if: matrix.os != 'windows'
        run: |
          tar -czvf qiniu_doc_checker.tar.gz qiniu_doc_checker config.yaml

      - name: Upload binary file to release draft
        if: matrix.os == 'windows'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: qiniu_doc_checker.zip
          asset_name: qiniu_doc_checker-${{ matrix.os }}-${{ env.version }}.zip
          asset_content_type: application/octet-stream

      - name: Upload binary file to release draft
        if: matrix.os == 'ubuntu'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: qiniu_doc_checker.tar.gz
          asset_name: qiniu_doc_checker-linux-${{ env.version }}.tar.gz
          asset_content_type: application/octet-stream

      - name: Upload binary file to release draft
        if: matrix.os == 'macos'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: qiniu_doc_checker.tar.gz
          asset_name: qiniu_doc_checker-${{ matrix.os }}-${{ env.version }}.tar.gz
          asset_content_type: application/octet-stream