name: Release qiniu-doc-checker

on:
  push:
    tags:
      - v*

permissions: write-all

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
          body: |
            Release Notes

  build_and_upload:
    name: Build and Upload
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1

      - name: Set version by tag
        id: set-version-by-tag
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

      # 查看Dart版本
      - name: Report version
        run: dart --version

      # 导入依赖
      - name: Install dependencies
        run: dart pub get

      # 编译二进制
      - name: Compile
        run: |
          mkdir output
          dart compile exe bin/qiniu_doc_checker.dart -o qiniu_doc_checker.exe
          zip qiniu_doc_checker.zip qiniu_doc_checker.exe

      - name: Upload binary file to release draft
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: qiniu_doc_checker.zip
          asset_name: qiniu_doc_checker-${{ matrix.os }}-${{ steps.set-version-by-tag.outputs.version }}.zip
          asset_content_type: application/octet-stream